# ===============================================================
# 🌐 S3 Cloud ETL Pipeline Configuration File
# ---------------------------------------------------------------
# Define your S3 source, sync behavior, and download filters here.
# Compatible with: s3_downloader_pipeline.py
# Author: Ashutosh Singh
# ===============================================================

# 📦 S3 Configuration
s3:
  prod-completed:                # (REQUIRED) S3 bucket name (e.g., healthcare-data-bucket)
    - 2025-05-30/                # Prefix/folder inside bucket. Must end with '/'.
    - 2025-03-01/                # Add more prefixes as needed.

# 🔄 Sync Mode Configuration
sync:
  loc_download: ../downloads     # (REQUIRED) Local directory to save downloaded files.
  mode: incremental              # Options:
                                 #   - full_refresh: Download all files
                                 #   - incremental: Only new/updated files
                                 #   - mirror: Match S3 exactly (delete local extras)
  threads: 8                     # Number of parallel download threads (default: 12)

# 🎯 File Filters
filters:
  include_extensions:            # Only download files with these extensions
    - .mp4
    - .xlsx
  exclude_files:                 # Skip these exact filenames (optional)
    - skip_this_file.csv